### PR TITLE
Include language classname for Rouge highlighting

### LINKED ISSUE #328: Feature Request: Include CSS classname for language in syntax-highlighted code blocks
RedCarpet includes <code>class="language-_blah_"</code> in the `<code>` tag for a syntax-highlighted code block with language specified.

This can be used to highlight and label code blocks by language, as I do [in my blog](http://blog.slaks.net/2015-06-30/code-snippets-impossible-code).

I'd like to add this classname to Kramdown too.

### PR DESCRIPTION
**Pull request by SLaks**
Fixes #328 (though only for Rouge)

### CODE REVIEW

**Comment by SLaks** [comment]
Travis is failing because the Kramdown round-tripper doesn't actually handle other options.

It cannot extract the language from the HTML input (as of this PR, this is no longer impossible), and it duplicates classnames if a non-default `css_class` is specified (it should remove the extra class that Rouge emits).

I'll delete the bad test.

**Comment by SLaks** [comment]
This PR is now green (the Travis build is failing on Ruby 1.8.7 because Rake no longer supports it).

Can you please take a look?

**Comment by parkr** [comment]
@SLaks Is this based on the latest changes in `gettalong:master`? I believe many were fixed for v1.8.7, or it was dropped.

**Comment by SLaks** [comment]
Yes; my branch is up to date.
https://github.com/gettalong/kramdown/blob/master/.travis.yml#L3

**Comment by gettalong** [comment]
Obsolete due to commit 3d2b8714ba6f78cd9d856c23d4e0369a4e2efb46.

**Pull request closed without merging**
