### PR TITLE
Frozen string literals throughout

### PR DESCRIPTION
**Pull request by glebm**
This will be the default in Ruby 3.
This change is *dangerous*, as there may be cases not covered by tests.

### CODE REVIEW

**Comment by gettalong** [comment]
Thanks for this pull request but I have to decline at the moment. I may change kramdown to use frozen strings in the future but not right now.

**Comment by plentz** [comment]
@gettalong do you think that this is a good time to start changing things to use frozen string literals?

**Comment by gettalong** [comment]
No, as @glebm wrote: It's a big change and right now I don't have the time.

**Comment by plentz** [comment]
hum, ok. When you think it's a good time, ping me - I can offer some help.

**Comment by glebm** [comment]
To save time, consider merging this and releasing a pre-release gem, e.g. `1.18.0.beta`. 

Then wait for a couple of months to see if any bugs come up.

**Comment by gettalong** [comment]
@glebm FYI frozen string literals are now active with the latest commits.

**Pull request closed without merging**
